# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SpotifyClient' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpotifyClient
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '~> 3.0'
end
